DOCKERUSER?=sigsci
DOCKERNAME?=sigsci-apache-ubuntu1604
DOCKERTAG?=latest
SIGSCI_ACCESSKEYID?=SETME
SIGSCI_SECRETACCESSKEY?=SETME
SIGSCI_HOSTNAME?=alpine35
DOCKERMOUNT?="/var/run/sigsci/agent.sock"
SIGSCI_MAX_PROCS?=0

build:
	./getAgent.sh
	docker build -t $(DOCKERUSER)/$(DOCKERNAME):$(DOCKERTAG) .

build-no-cache:
	./getAgent.sh
	docker build --no-cache -t $(DOCKERUSER)/$(DOCKERNAME):$(DOCKERTAG) .

run:
	docker run -p 3000:3000 --name $(DOCKERNAME) -d -e SIGSCI_HOSTNAME=$(SIGSCI_HOSTNAME)  -e SIGSCI_ACCESSKEYID="$(SIGSCI_ACCESSKEYID)" -e SIGSCI_SECRETACCESSKEY="$(SIGSCI_SECRETACCESSKEY)" -e SIGSCI_MAX_PROCS=$(SIGSCI_MAX_PROCS) $(DOCKERUSER)/$(DOCKERNAME):$(DOCKERTAG)

deploy:
	docker push $(DOCKERUSER)/$(DOCKERNAME):$(DOCKERTAG)
